# Numpy

In [2]:
#pip install numpy

In [3]:
import numpy as np

In [4]:
a=np.array(80)
print(a)
print(type(a))
print(a.ndim)

80
<class 'numpy.ndarray'>
0


In [5]:
b=np.array([1,2,3,4])
print(b)
print(type(b))
print(b.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [7]:
c=np.array([[1,2,3],[4,5,5]])
print(c)
print(type(c))
print(c.ndim)

[[1 2 3]
 [4 5 5]]
<class 'numpy.ndarray'>
2


In [8]:
d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)
print(type(d))
print(d.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>
3


In [10]:
#list
a=[1,2,3,4]
b=[5,6,7,8]
print(a+b)

[1, 2, 3, 4, 5, 6, 7, 8]


In [11]:
#array
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a+b)

[ 6  8 10 12]


In [12]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a*b)

[ 5 12 21 32]


In [13]:
c=np.sum(a)
print(c)

10


In [14]:
d=np.mean(a)
print(d)

2.5
